video_input:
  path: "/mnt/synology/BWVs/1_1000"
  # path: "./video_samples/"

gpus:
  - cuda:0
  - cuda:1
  - cuda:2

threads_per_gpu: 16

phases:
  - model:
      name: "VL3-SigLIP-NaViT"
      path: "models/VL3-SigLIP-NaViT"
      source: "folder"
      features: ["video_embedding"]

    db:
      type: "milvus"
      base_path: "/mnt/synology/BWVs/db/milvus"
      batch_size: 1000
      collections:
        - name: "video_embedding_collection"
          fields:
            - name: id
              dtype: INT64
              is_primary: true
              auto_id: true
            - name: frame_id
              dtype: INT16
            - name: row_idx
              dtype: INT16
            - name: col_idx
              dtype: INT16
            - name: embeddings
              dtype: FLOAT_VECTOR
              dim: 1152