video_input:
  batch: first_10_videos
  path: 
    - "/mnt/synology/BWVs/first_10_videos"
    - "/mnt/synology/BWVs/second_400_videos"

gpus:
  - cuda:0
  - cuda:1
  - cuda:2

threads_per_gpu: 1

phases:
  - model:
      name: "VL3-SigLIP-NaViT"
      path: "models/VL3-SigLIP-NaViT"
      source: "folder"
      features: ["video_embedding"]