model:
  name: "VL3-SigLIP-NaViT"
  path: "models/VL3-SigLIP-NaViT"
  source: "huggingface"
  features: ["video_embedding"]

video_input:
  path: "./video_samples/"

gpus:
  - mps

db:
  type: "milvus"
  name: "navit_video_feature.db"
  batch_size: 1000
  collections:
    - name: "video_embedding_collection"
      fields:
        - name: id
          dtype: INT64
          is_primary: true
          auto_id: true
        - name: video_path
          dtype: VARCHAR
          max_length: 512
        - name: frame_id
          dtype: INT16
        - name: row_idx
          dtype: INT16
        - name: col_idx
          dtype: INT16
        - name: embeddings
          dtype: FLOAT_VECTOR
          dim: 1152