video_input:
  path: "/mnt/synology/BWVs/1_1000"
  # path: "./video_samples/"

gpus:
  - cuda:0
  - cuda:1
  - cuda:2

threads_per_gpu: 8

writers: 8

phases:
  - model:
      name: "VL3-SigLIP-NaViT"
      path: "models/VL3-SigLIP-NaViT"
      source: "folder"
      features: ["video_embedding"]

    db:
      type: "milvus"
      name: "navit_video_feature_first_batch_test.db"
      batch_size: 1000
      host: "127.0.0.1"
      port: "19530"
      collections:
        - name: "video_embedding_collection"
          fields:
            - name: id
              dtype: INT64
              is_primary: true
              auto_id: true
            - name: video_path
              dtype: VARCHAR
              max_length: 512
            - name: frame_id
              dtype: INT16
            - name: row_idx
              dtype: INT16
            - name: col_idx
              dtype: INT16
            - name: embeddings
              dtype: FLOAT_VECTOR
              dim: 1152