video_input:
  batch: first_10_videos
  path: 
    - "/mnt/synology/BWVs/fourth_900_videos"
    - "/mnt/synology/BWVs/fifth_45_videos"
    - "/mnt/synology/BWVs/sixth_709_videos"
    - "/mnt/synology/BWVs/seventh_322_videos"
    - "/mnt/synology/BWVs/eighth_322_videos/1-60"
    # - "/mnt/synology/BWVs/eighth_322_videos/61-120"
    - "/mnt/synology/BWVs/eighth_322_videos/121-180"
    - "/mnt/synology/BWVs/eighth_322_videos/181-240"
    - "/mnt/synology/BWVs/eighth_322_videos/241-300"
    - "/mnt/synology/BWVs/eighth_322_videos/301-322"
    - "/mnt/synology/BWVs/ninth_64_videos"
    # - "/mnt/synology/BWVs/7001-8000"
    # - "/mnt/synology/BWVs/8001-9000"
    # - "/mnt/synology/BWVs/11651-11950"
    # - "/mnt/synology/BWVs/10001-11000"
    # - "/mnt/synology/BWVs/11001-11650"
    # - "/mnt/synology/BWVs/9250-10000"
    # - "/mnt/synology/BWVs/1_1000"
    # - "/mnt/synology/BWVs/1001-2000"
    # - "/mnt/synology/BWVs/14751-15000"
    # - "/mnt/synology/BWVs/12001-13000"
    # - "/mnt/synology/BWVs/13001-14000"
    # - "/mnt/synology/BWVs/14001-14490"
    # - "/mnt/synology/BWVs/15001-16000"
    # - "/mnt/synology/BWVs/16001-17000"
    # - "/mnt/synology/BWVs/17001-17450"
    # - "/mnt/synology/BWVs/20701-21000"
    # - "/mnt/synology/BWVs/20401-20700"
    # - "/mnt/synology/BWVs/18001-19000"
    # - "/mnt/synology/BWVs/19001-20000"
    # - "/mnt/synology/BWVs/20001-20400"
    # - "/mnt/synology/BWVs/11951-12000"
    # - "/mnt/synology/BWVs/9001-9250"
    # - "/mnt/synology/BWVs/21276-21550"
    # - "/mnt/synology/BWVs/21001-21275"
    # - "/mnt/synology/BWVs/21551-22000"
    # - "/mnt/synology/BWVs/22001-23000"
    # - "/mnt/synology/BWVs/2301-3000"
    # - "/mnt/synology/BWVs/2001-2300"
    # - "/mnt/synology/BWVs/3001-4000"
    # - "/mnt/synology/BWVs/4001-4500"
    # - "/mnt/synology/BWVs/4501-5000"
    # - "/mnt/synology/BWVs/5001-6000"
    # - "/mnt/synology/BWVs/6001-6800"
    # - "/mnt/synology/BWVs/6801-7000"
    # - "/mnt/synology/BWVs/23001-24000"
    # - "/mnt/synology/BWVs/24001-25000"
    # - "/mnt/synology/BWVs/26001-27000"
    # - "/mnt/synology/BWVs/27001-28000"
    # - "/mnt/synology/BWVs/30001-31000"
    # - "/mnt/synology/BWVs/29001-30000"
    # - "/mnt/synology/BWVs/32001-33000"
    # - "/mnt/synology/BWVs/34001-35000"
    # - "/mnt/synology/BWVs/35001-36000"
    # - "/mnt/synology/BWVs/37001-38000"
    # - "/mnt/synology/BWVs/38001-38415"
    # - "/mnt/synology/BWVs/14491-14750_(260_vids)"
    # - "/mnt/synology/BWVs/17451-17725_(275_videos)"
    # - "/mnt/synology/BWVs/17726-18000_(275_videos)"
    # - "/mnt/synology/BWVs/25001-26000_P3"
    # - "/mnt/synology/BWVs/25001-26000_P2"
    # - "/mnt/synology/BWVs/25001-26000_P1_of_4"
    # - "/mnt/synology/BWVs/25001-26000_P4_of_4"
    # - "/mnt/synology/BWVs/28001-29000_P2_of_4"
    # - "/mnt/synology/BWVs/28001-29000_P1_of_4"
    # - "/mnt/synology/BWVs/28001-29000_P3_of_4"
    # - "/mnt/synology/BWVs/28001-29000_P4_of_4"
    # - "/mnt/synology/BWVs/31001-32000_P2"
    # - "/mnt/synology/BWVs/31001-32000_P3"
    # - "/mnt/synology/BWVs/33001-34000_P1"
    # - "/mnt/synology/BWVs/31001-32000_P1"
    # - "/mnt/synology/BWVs/36001-37000_P2"
    # - "/mnt/synology/BWVs/36001-37000_P3"
    # - "/mnt/synology/BWVs/33001-34000_P2"
    # - "/mnt/synology/BWVs/36001-37000_P1"
    # - "/mnt/synology/BWVs/36001-37000_P4"

gpus:
  - cuda:0

threads_per_gpu: 1

phases:
  - model:
      base_dir: "OpenSmile"
      name: "opensmile"
      path: "opensmile"
      source: "folder"
      features: ["open_smile_features"]
      open_smile_config:
        feature_set: 
          - "eGeMAPSv02"
          - "emobase"
        feature_levels: 
          - "LowLevelDescriptors"
    