video_input:
  batch: first_10_videos
  path: 
    - "/mnt/synology/BWVs/fifth_45_videos"

gpus:
  - cuda:2

threads_per_gpu: 1

phases:
  - model:
      base_dir: "Phi-4-mel"
      name: "Phi-4-mel"
      path: "models/VL3-SigLIP-NaViT"
      source: "folder"
      features: ["speech_mels_features"]