video_input:
  # path: "/mnt/synology/BWVs/first_10_videos"
  path: "./video_samples/"

gpus:
  - cuda:0

threads_per_gpu: 1

phases:
  - model:
      name: "VL3-SigLIP-NaViT"
      path: "models/VL3-SigLIP-NaViT"
      source: "folder"
      features: ["video_embedding_pooling"]