video_input:
  batch: first_10_videos
  path: "/data2/shihheng/feature_pipeline/feature_pipeline_example/"

gpus:
  - cuda:0

threads_per_gpu: 1

phases:
  - model:
      name: "WavLM-Large"
      path: "models/WavLM-Large"
      source: "folder"
      features: ["speech_mels_features"]
    